### ISSUE TITLE
🚀 [Feature] : Covert it to svelte components with the same design

### ISSUE THREAD

**Issue by xuelink** [languageXchange/token-website#1]
**Is your feature request related to a problem? Please describe.**
I am looking to convert a single `index.html` file into Svelte components while maintaining the same design. This will allow for better component management, reusability, and easier maintenance.

**Describe the solution you'd like**
I would like the `index.html` file to be broken down into individual Svelte components, with each part of the HTML being converted into a corresponding Svelte component. The resulting Svelte components should retain the same design and functionality as the original HTML file.

**Describe alternatives you've considered**
An alternative could be to use another JavaScript framework like React or Vue, but Svelte is preferred due to its simplicity and performance benefits.

**Additional context**
The `index.html` file contains the entire structure and styling for the current design. Converting it to Svelte components should preserve the existing layout and styles while enhancing the codebase's modularity. Screenshots or additional context can be provided if needed.

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
@jakebogan01 , Are you interested in ?

**Comment by xuelink** [comment]
_Optional:_ If you think that [tailwind css](https://tailwindcss.com/) fits here well, you also can implement it here.

**Comment by jakebogan01** [comment]
@xuelink Yeah I can see what I can do next week with this 👍

**Comment by xuelink** [comment]
> @xuelink Yeah I can see what I can do next week with this 👍

Going to be awesome ! :) How much you can do im ok then, I can join your PR as well.
Feel free to add this website to your portfolio ;) Thanks you again @jakebogan01

**Comment by jakebogan01** [comment]
@xuelink No problem, I'll start on it tomorrow

**Comment by xuelink** [comment]
Take your time @jakebogan01 😉

**Comment by jakebogan01** [comment]
@xuelink I made a PR [here](https://github.com/langx/token-website/pull/4) However, I wasn't able to finish the main titles and animation. Things like SplitText I don't have access to, in order to use it as a module

**Comment by Honzoraptor31415** [comment]
> @xuelink I made a PR [here](https://github.com/langx/token-website/pull/4) However, I wasn't able to finish the main titles and animation. Things like SplitText I don't have access to, in order to use it as a module

So from what I understand, those modules like SplitText are just in the previous website, but we'd need a special lib for it to work with Svelte?

Or we coule also just code it all from scratch :D

**Comment by xuelink** [comment]
> > [@xuelink](https://github.com/xuelink) I made a PR [here](https://github.com/langx/token-website/pull/4) However, I wasn't able to finish the main titles and animation. Things like SplitText I don't have access to, in order to use it as a module
> 
> So from what I understand, those modules like SplitText are just in the previous website, but we'd need a special lib for it to work with Svelte?
> 
> Or we coule also just code it all from scratch :D

Without adding special lib, can we do as components with html and css ? if its not gonna be, i can close that issue that we can contiue with simple HTML and CSS with index.html not a big deal.

**Comment by Honzoraptor31415** [comment]
> > > [@xuelink](https://github.com/xuelink) I made a PR [here](https://github.com/langx/token-website/pull/4) However, I wasn't able to finish the main titles and animation. Things like SplitText I don't have access to, in order to use it as a module
> > 
> > 
> > So from what I understand, those modules like SplitText are just in the previous website, but we'd need a special lib for it to work with Svelte?
> > Or we coule also just code it all from scratch :D
> 
> Without adding special lib, can we do as components with html and css ? if its not gonna be, i can close that issue that we can contiue with simple HTML and CSS with index.html not a big deal.

Yeah, that actually sounds pretty good. We may look into the special libraries later, but now just get the basics working.

**Comment by xuelink** [comment]
> > > > [@xuelink](https://github.com/xuelink) I made a PR [here](https://github.com/langx/token-website/pull/4) However, I wasn't able to finish the main titles and animation. Things like SplitText I don't have access to, in order to use it as a module
> > > 
> > > 
> > > So from what I understand, those modules like SplitText are just in the previous website, but we'd need a special lib for it to work with Svelte?
> > > Or we coule also just code it all from scratch :D
> > 
> > 
> > Without adding special lib, can we do as components with html and css ? if its not gonna be, i can close that issue that we can contiue with simple HTML and CSS with index.html not a big deal.
> 
> Yeah, that actually sounds pretty good. We may look into the special libraries later, but now just get the basics working.

OK, When it will be in case later, we can take a look here again but for now, i am also closing this issue as well.
