### ISSUE TITLE
🚀 [Feature] : Better README.md

### ISSUE THREAD

**Issue by xuelink** [languageXchange/token-website#2]
**Is your feature request related to a problem? Please describe.**
The current `README.md` lacks detailed information, making it difficult for new users to understand the project's purpose, how to set it up, and how to contribute. This can be frustrating and may hinder adoption and collaboration.

**Describe the solution you'd like**
I would like a comprehensive `README.md` that includes the following sections:
- Project Overview: A brief description of the project and its goals.
- Features: A list of key features and functionalities.
- Installation: Step-by-step instructions on how to set up the project locally.
- Usage: Examples and explanations of how to use the project.
- Contributing: Guidelines for contributing to the project.
- License: Information about the project's license.
- Contact: How to get in touch with the project maintainers.

**Describe alternatives you've considered**
An alternative could be to create a separate documentation website for detailed guides and tutorials, but enhancing the `README.md` is a more immediate and accessible solution.

**Additional context**
Including badges for build status, dependencies, and other relevant information could also enhance the `README.md`. Screenshots or additional visual aids may be helpful to illustrate key points.

_If you want to speed up the process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
Please add README following sections and make it better readibility as well.

I took from langx/website repo https://github.com/langx/website/blob/main/README.md?plain=1

Can you please update this readme.md as well like the langx/website readme.md

```md

## Table of Contents
- [Getting Started](#getting-started)
- [Contributing](#contributing)
- Stats ...
  - Stargazers
  - Contributors
- [License](#license)

## Getting started

To clone this project, simply run the following command:


# clone this repo
git clone  https://github.com/langx/website

## Contributing

We welcome contributions from the community! If you'd like to contribute to LangX, please fork our repository and submit a pull request. We'll review your changes and merge them if they meet our guidelines. Thank you for helping to make LangX even better!

We'll review your changes and merge them if they meet our guidelines. Thank you for helping to make LangX even better!

LangX is an open source project and we welcome contributions from the community. If you're interested in contributing, please check out our GitHub repository for more information.

## Versioning

LangX uses [Semantic Versioning](https://semver.org/) for versioning. For the versions available, see the [tags on this repository](https://github.com/langx/website/releases).

## Stats

### Stargazers

[![Stargazers over time](https://starchart.cc/langx/website.svg?variant=adaptive)](https://starchart.cc/langx/website)

### Contributors

[![GitHub Contributor Over Time](https://contributor-overtime-api.git-contributor.com/contributors-svg?chart=contributorOverTime&repo=langx/token-website)](https://git-contributor.com?chart=contributorOverTime&repo=langx/token-website)

[![GitHub Contributors Image](https://contrib.rocks/image?repo=langx/token-website)](https://github.com/langx/token-website/graphs/contributors)

## License

LangX is released under the [MIT License](./LICENSE). If you use this project, please include the license file in your distribution.

```

**Comment by Caluryth** [comment]
Will do!
